name: Build images

on:
  workflow_dispatch:
    inputs:
      hostname:
        description: "Hostname (will be advertised via mDNS as <hostname>.local)"
        required: true
        default: "evcc"
      evcc_channel:
        description: "evcc APT channel (stable or unstable)"
        required: true
        default: "stable"
      release:
        description: "Debian release for Armbian rootfs"
        required: true
        default: "bookworm"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    strategy:
      fail-fast: false
      matrix:
        board: ["rpi4b", "rpi5b", "radxa-e52c", "nanopi-r3s"]
    name: Build ${{ matrix.board }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare Docker and workspace
        run: |
          mkdir -p dist logs
          sudo apt-get update
          sudo apt-get install -y qemu-user-static binfmt-support xz-utils zip

      - name: Build image
        env:
          HOSTNAME: ${{ inputs.hostname }}
          EVCC_CHANNEL: ${{ inputs.evcc_channel }}
          RELEASE: ${{ inputs.release }}
        run: |
          set -euo pipefail
          chmod +x ./scripts/build-armbian.sh
          echo "::group::Building for ${{ matrix.board }}"
          bash ./scripts/build-armbian.sh \
            --board "${{ matrix.board }}" \
            --release "$RELEASE" \
            --hostname "$HOSTNAME" \
            --evcc-channel "$EVCC_CHANNEL"
          echo "::endgroup::"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: armbian-image-${{ matrix.board }}
          path: |
            dist/**/${{ matrix.board }}/**
          if-no-files-found: error
