name: Build images

on:
  workflow_dispatch:
    inputs:
      board:
        description: "Target board to build (or all)"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - rpi4b
          - rpi5b
          - radxa-e52c
          - nanopi-r3s
      evcc_channel:
        description: "evcc APT channel (stable or nightly)"
        required: true
        default: "stable"
        type: choice
        options:
          - stable
          - nightly
      release:
        description: "Debian release for Armbian rootfs"
        required: true
        default: "bookworm"

jobs:
  prepare:
    runs-on: depot-ubuntu-24.04-arm-4
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Compute matrix
        id: set-matrix
        run: |
          choice='${{ inputs.board }}'
          case "$choice" in
            all)      MATRIX='["rpi4b","rpi5b","radxa-e52c","nanopi-r3s"]' ;;
            rpi4b)    MATRIX='["rpi4b"]' ;;
            rpi5b)    MATRIX='["rpi5b"]' ;;
            radxa-e52c) MATRIX='["radxa-e52c"]' ;;
            nanopi-r3s) MATRIX='["nanopi-r3s"]' ;;
            *) echo "Unknown board: $choice" >&2; exit 1 ;;
          esac
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT

  build:
    needs: prepare
    runs-on: depot-ubuntu-24.04-arm-4
    timeout-minutes: 360
    strategy:
      fail-fast: false
      matrix:
        board: ${{ fromJSON(needs.prepare.outputs.matrix) }}
    name: Build ${{ matrix.board }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare Docker and workspace
        run: |
          mkdir -p dist logs
          sudo apt-get update
          sudo apt-get install -y qemu-user-static binfmt-support xz-utils zip

      - name: Build image
        env:
          EVCC_CHANNEL: ${{ inputs.evcc_channel }}
          RELEASE: ${{ inputs.release }}
        run: |
          set -euo pipefail
          chmod +x ./scripts/build-armbian.sh
          echo "::group::Building for ${{ matrix.board }}"
          bash ./scripts/build-armbian.sh \
            --board "${{ matrix.board }}" \
            --release "$RELEASE" \
            --evcc-channel "$EVCC_CHANNEL"
          echo "::endgroup::"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: armbian-image-${{ matrix.board }}
          path: |
            dist/**/${{ matrix.board }}/**
          if-no-files-found: error
